# Generated by Django 5.0 on 2023-12-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScanDate', models.DateTimeField()),
                ('NetworkIPStart', models.GenericIPAddressField(protocol='IPv4')),
                ('NetworkIPEnd', models.GenericIPAddressField(protocol='IPv4')),
                ('PortStart', models.PositiveSmallIntegerField()),
                ('PortEnd', models.PositiveSmallIntegerField()),
                ('UserIP', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TraceDate', models.DateTimeField()),
                ('IPAddress', models.GenericIPAddressField(protocol='IPv4')),
                ('UserIP', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField(protocol='IPv4')),
                ('ResponseTime', models.PositiveSmallIntegerField()),
                ('Scan', models.ManyToManyField(to='cyberscan.scan')),
            ],
        ),
        migrations.CreateModel(
            name='PortsScanned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Port', models.PositiveSmallIntegerField()),
                ('Status', models.BooleanField()),
                ('ScanResult', models.ManyToManyField(to='cyberscan.scanresult')),
            ],
        ),
        migrations.CreateModel(
            name='TraceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HopIP', models.GenericIPAddressField(protocol='IPv4')),
                ('HopReply', models.PositiveSmallIntegerField()),
                ('Trace', models.ManyToManyField(to='cyberscan.trace')),
            ],
        ),
    ]
