# Generated by Django 5.0 on 2023-12-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceresult',
            name='Hop',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
