# Generated by Django 5.0 on 2023-12-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0002_traceresult_hop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='NetworkIPEnd',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='NetworkIPStart',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='PortEnd',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='PortStart',
        ),
        migrations.AddField(
            model_name='scan',
            name='NetworkIPs',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='Ports',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
