# Generated by Django 5.0 on 2023-12-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0003_remove_scan_networkipend_remove_scan_networkipstart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='ResponseTime',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='Hostname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
