# Generated by Django 5.0 on 2023-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0004_remove_scanresult_responsetime_scanresult_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portsscanned',
            name='Status',
            field=models.CharField(max_length=20),
        ),
    ]
