# Generated by Django 5.0 on 2023-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0005_alter_portsscanned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='Status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
