# Generated by Django 5.0 on 2023-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0006_scanresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portsscanned',
            name='ScanResult',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='PortsScanned',
            field=models.ManyToManyField(to='cyberscan.portsscanned'),
        ),
    ]
