# Generated by Django 5.0 on 2023-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberscan', '0007_remove_portsscanned_scanresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='PortsScanned',
        ),
        migrations.AddField(
            model_name='portsscanned',
            name='ScanResult',
            field=models.ManyToManyField(to='cyberscan.scanresult'),
        ),
    ]
